CSS Conf EU 2018
EddyVinck/ConfTalks pull request #8
Opened 2019-10-20 05:27 UTC by josectobar

2019-10-20 05:28 UTC, josectobar commented
#8

2019-10-20 09:07 UTC, EddyVinck commented
Hi @josectobar! Thanks for your contribution! I can merge this in if you fix the merge conflicts and update the unique IDs.

2019-10-20 09:10 UTC, EddyVinck requested changes

2019-10-20 09:10 UTC, EddyVinck commented on client/data/conferences.json
> +    "2": {
To fix the merge conflicts, merge the original master branch and update your IDs. Please re-order them as well so the numbers are in a logical order.

2019-10-20 09:10 UTC, EddyVinck commented on client/data/speakers.json
> +    "0": {
To fix the merge conflicts, merge the original master branch and update your IDs. Please re-order them as well so the numbers are in a logical order.

Also please turn off the formatting.

2019-10-20 09:10 UTC, EddyVinck commented on client/data/talks.json
> +    "50": {
To fix the merge conflicts, merge the original master branch and update your IDs. Please re-order them as well so the numbers are in a logical order.

2019-10-20 19:18 UTC, EddyVinck commented
@josectobar Please let me know if this is something you'd still like to work on

2019-10-20 19:19 UTC, josectobar commented
I do, give me a couple of hours.

On Sun, Oct 20, 2019 at 1:18 PM Eddy <notifications@github.com> wrote:

> @josectobar <https://github.com/josectobar> Please let me know if this is
> something you'd still like to work on
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/EddyVinck/ConfTalks/pull/8?email_source=notifications&email_token=AFCDEPETXJHOFTEEYPX47S3QPSVG3A5CNFSM4JCSXCO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBYRSQI#issuecomment-544282945>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFCDEPAV44JUYNAB4Z66UVDQPSVG3ANCNFSM4JCSXCOQ>
> .
>

2019-10-20 20:41 UTC, EddyVinck commented on client/data/talks.json
> -      "main_title": "Any Site can be a Progressive Web App",
```
 "main_title": "Any Site can be a Progressive Web App",	
      "alternative_titles": [],	
      "categories": [1, 8],	
      "video_url": "https://www.youtube.com/watch?v=GXv4W94qsQ0",	
      "video_upload_date": "2018-06-11",
```
I think you accidentally deleted this

2019-10-20 20:55 UTC, josectobar commented on client/data/talks.json
> -      "main_title": "Any Site can be a Progressive Web App",
sorry.

2019-10-21 07:31 UTC, EddyVinck commented on client/data/talks.json
> -      "main_title": "Any Site can be a Progressive Web App",
No problem! It happens

2019-10-21 18:51 UTC, EddyVinck commented
@josectobar Since I merged some larger commits in first I updated the IDs and such for your PR myself. Thank you for your contribution! Remember to join our [Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) and [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you haven't already :slightly_smiling_face: 

I'm going to merge this in now

2019-10-21 18:51 UTC, merged

2019-10-21 18:52 UTC, dios-david commented on client/data/talk_categories.json
> +      "name": "Design Systems",
@EddyVinck do we need both `UX` and `Design Systems`?